#!/bin/bash
echo "Configuring GPIO pins"
config-pin p9.12 gpio
config-pin p9.15 gpio
config-pin -q p8.16
config-pin -l p8.16
config-pin p8.16 gpio_pu
config-pin -q p8.16
echo "Starting build for project.cpp"
g++ project.cpp Analogin.cpp GPIO.cpp -lpaho-mqtt3c -o project -pthread
echo "Finishing build for project.cpp"
